spring.application.name=user-management
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27018/users
spring.data.mongodb.database=users
server.port=8085

# Keycloak Configuration
keycloak.adminClientId=admin-cli
keycloak.adminClientSecret=eBWPFbj9uHXPL5ML165g0YuX2eqo9jlI
keycloak.urls.auth=http://localhost:8180
keycloak.realm=surplus
jwt.auth.converter.resource-id=account


# Spring Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/surplus
