spring.application.name=user-management
# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27018/users
spring.data.mongodb.database=users
server.port=8085

# Keycloak Configuration
keycloak.adminClientId=surplus-client
keycloak.adminClientSecret=5ZKddttd05J6mG7G8SqtgfedsuUjAg5C
keycloak.urls.auth=http://localhost:8180
keycloak.realm=surplus
jwt.auth.converter.resource-id=surplus-client


# Spring Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/surplus
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/surplus/protocol/openid-connect/certs
